name: Flat
on:
  schedule:
    - cron: 31 9 * * 1-5
  workflow_dispatch: 
  push:
    paths:
      - .github/workflows/flat.yml
      - ./postprocess.ts
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.10.x
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://corsproxy.io/?https://www.ons.gov.uk/economy/inflationandpriceindices/bulletins/housepriceindex/previousReleases/data
          downloaded_filename: ons.json
          postprocess: ./postprocess.ts
